# Conhecendo a base

O diabetes é uma doença crônica grave na qual os indivíduos perdem a capacidade de regular efetivamente os níveis de glicose no sangue e pode levar a uma redução na qualidade de vida e na expectativa de vida.

O Sistema de Vigilância de Fatores de Risco Comportamentais (BRFSS) é uma pesquisa telefônica relacionada à saúde que é coletada anualmente pelo CDC (Centro de Controle e Prevenção de Doenças dos Estados Unidos). A cada ano, a pesquisa coleta respostas de milhares de americanos sobre comportamentos de risco relacionados à saúde, condições crônicas de saúde e o uso de serviços preventivos. Para este projeto, foi utilizado conjunto de dados disponível no Kaggle para o ano de 2015. 

https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset

In [ ]:
from src.config import DADOS_ORIGINAIS, DADOS_TRATADOS

import pandas as pd

pd.set_option('display.max_columns', None)

df_diabetes = pd.read_csv(DADOS_ORIGINAIS, compression='zip')

df_diabetes.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [2]:
df_diabetes.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

## Verificando a estrutura da base

Nesta etapa, verificamos informações gerais das colunas, como tipos de dados e quantidade de registros.

**Por que fazer isso?**
Antes de tratar os dados, precisamos saber como eles estão armazenados e identificar possíveis problemas.

In [3]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_binary       70692 non-null  float64
 1   HighBP                70692 non-null  float64
 2   HighChol              70692 non-null  float64
 3   CholCheck             70692 non-null  float64
 4   BMI                   70692 non-null  float64
 5   Smoker                70692 non-null  float64
 6   Stroke                70692 non-null  float64
 7   HeartDiseaseorAttack  70692 non-null  float64
 8   PhysActivity          70692 non-null  float64
 9   Fruits                70692 non-null  float64
 10  Veggies               70692 non-null  float64
 11  HvyAlcoholConsump     70692 non-null  float64
 12  AnyHealthcare         70692 non-null  float64
 13  NoDocbcCost           70692 non-null  float64
 14  GenHlth               70692 non-null  float64
 15  MentHlth              70692 non-null  float64
 16  PhysHlth              70692 non-null  float64
 17  DiffWalk              70692 non-null  float64
 18  Sex                   70692 non-null  float64
 19  Age                   70692 non-null  float64
 20  Education             70692 non-null  float64
 21  Income                70692 non-null  float64
dtypes: float64(22)
memory usage: 11.9 MB

## Traduzindo os nomes das colunas

Aqui trocamos os nomes originais das colunas por nomes em português e mais fáceis de entender.

traduzindo as colunas para facilitar o entendimento

In [4]:
df_diabetes.columns = [
    "Diabetes",
    "PressaoAlta",
    "ColesterolAlto",
    "ColesterolExame",
    "IMC",
    "Fumante",
    "AVC",
    "ProblemaCardiaco",
    "AtividadeFisica",
    "ComeFrutas",
    "ComeLegumes",
    "ConsumoBebidaAlcoolica",
    "PlanoSaude",
    "SemDinheiroConsultas",
    "SaudeGeral",
    "DiasProblemasMentais",
    "DiasProblemasFisicos",
    "DificuldadeAndar",
    "Genero",
    "FaixaIdade",
    "Ensino",
    "FaixaRenda",
]

## Verificando os valores únicos

Essa informação ajuda a identificar quais colunas possuem apenas duas categorias e podem ser tratadas como variáveis binárias.

In [5]:
df_diabetes.nunique()

Diabetes                   2
PressaoAlta                2
ColesterolAlto             2
ColesterolExame            2
IMC                       80
Fumante                    2
AVC                        2
ProblemaCardiaco           2
AtividadeFisica            2
ComeFrutas                 2
ComeLegumes                2
ConsumoBebidaAlcoolica     2
PlanoSaude                 2
SemDinheiroConsultas       2
SaudeGeral                 5
DiasProblemasMentais      31
DiasProblemasFisicos      31
DificuldadeAndar           2
Genero                     2
FaixaIdade                13
Ensino                     6
FaixaRenda                 8
dtype: int64

## Identificando as colunas binárias

Aqui selecionamos as colunas que possuem exatamente dois valores diferentes.

**Por que fazer isso?**
Essas colunas representam situações com duas possibilidades e podem ser convertidas para categorias mais fáceis de interpretar.

In [6]:
colunas_binarias = df_diabetes.nunique()[df_diabetes.nunique() == 2].index.to_list()

colunas_binarias

['Diabetes',
 'PressaoAlta',
 'ColesterolAlto',
 'ColesterolExame',
 'Fumante',
 'AVC',
 'ProblemaCardiaco',
 'AtividadeFisica',
 'ComeFrutas',
 'ComeLegumes',
 'ConsumoBebidaAlcoolica',
 'PlanoSaude',
 'SemDinheiroConsultas',
 'DificuldadeAndar',
 'Genero']

## Criando uma cópia para o tratamento

Criamos uma cópia da base original para realizar as alterações.

**Por que fazer isso?**
Assim mantemos os dados originais preservados e fazemos o tratamento em uma versão separada.

In [7]:
df_diabetes_tratado = df_diabetes.copy()

df_diabetes_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Diabetes                70692 non-null  float64
 1   PressaoAlta             70692 non-null  float64
 2   ColesterolAlto          70692 non-null  float64
 3   ColesterolExame         70692 non-null  float64
 4   IMC                     70692 non-null  float64
 5   Fumante                 70692 non-null  float64
 6   AVC                     70692 non-null  float64
 7   ProblemaCardiaco        70692 non-null  float64
 8   AtividadeFisica         70692 non-null  float64
 9   ComeFrutas              70692 non-null  float64
 10  ComeLegumes             70692 non-null  float64
 11  ConsumoBebidaAlcoolica  70692 non-null  float64
 12  PlanoSaude              70692 non-null  float64
 13  SemDinheiroConsultas    70692 non-null  float64
 14  SaudeGeral              70692 non-null  float64
 15  DiasProblemasMentais    70692 non-null  float64
 16  DiasProblemasFisicos    70692 non-null  float64
 17  DificuldadeAndar        70692 non-null  float64
 18  Genero                  70692 non-null  float64
 19  FaixaIdade              70692 non-null  float64
 20  Ensino                  70692 non-null  float64
 21  FaixaRenda              70692 non-null  float64
dtypes: float64(22)
memory usage: 11.9 MB

## Transformando valores binários em categorias

Nesta etapa, os valores binários são transformados em categorias como **Sim** e **Não**. A coluna de gênero recebe categorias próprias.

**Por que fazer isso?**
Os valores ficam mais fáceis de entender e de interpretar durante a análise.

In [8]:
for coluna in colunas_binarias:
    if coluna != 'Genero':
        df_diabetes_tratado[coluna] = pd.Categorical(df_diabetes_tratado[coluna]).rename_categories(['Não', 'Sim'])
    else:
        df_diabetes_tratado[coluna] = pd.Categorical(df_diabetes[coluna]).rename_categories(['Femenino', 'Masculino'])

Conferindo o resultado do tratamento

In [9]:
df_diabetes_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Diabetes                70692 non-null  category
 1   PressaoAlta             70692 non-null  category
 2   ColesterolAlto          70692 non-null  category
 3   ColesterolExame         70692 non-null  category
 4   IMC                     70692 non-null  float64
 5   Fumante                 70692 non-null  category
 6   AVC                     70692 non-null  category
 7   ProblemaCardiaco        70692 non-null  category
 8   AtividadeFisica         70692 non-null  category
 9   ComeFrutas              70692 non-null  category
 10  ComeLegumes             70692 non-null  category
 11  ConsumoBebidaAlcoolica  70692 non-null  category
 12  PlanoSaude              70692 non-null  category
 13  SemDinheiroConsultas    70692 non-null  category
 14  SaudeGeral              70692 non-null  float64
 15  DiasProblemasMentais    70692 non-null  float64
 16  DiasProblemasFisicos    70692 non-null  float64
 17  DificuldadeAndar        70692 non-null  category
 18  Genero                  70692 non-null  category
 19  FaixaIdade              70692 non-null  float64
 20  Ensino                  70692 non-null  float64
 21  FaixaRenda              70692 non-null  float64
dtypes: category(15), float64(7)
memory usage: 4.8 MB

## Transformando outras variáveis em categorias

Aqui organizamos variáveis como saúde geral, faixa de idade, ensino e renda em categorias ordenadas.

**Por que fazer isso?**
Essas informações possuem uma ordem natural. Manter essa ordem ajuda o Python a representar corretamente a relação entre as categorias.

In [10]:
df_diabetes_tratado['SaudeGeral'] = pd.Categorical(
    df_diabetes_tratado['SaudeGeral'],
    ordered=True
).rename_categories(['Excelente', 'Muito boa', 'Boa', 'Aceitavel', 'Ruim'])

df_diabetes_tratado["FaixaIdade"] = pd.Categorical(
    df_diabetes_tratado["FaixaIdade"],
    ordered=True
).rename_categories(
    [
        "18-24",
        "25-29",
        "30-34",
        "35-39",
        "40-44",
        "45-49",
        "50-54",
        "55-59",
        "60-64",
        "65-69",
        "70-74",
        "75-79",
        "80+",
    ]
)

df_diabetes_tratado["Ensino"] = pd.Categorical(
    df_diabetes_tratado["Ensino"],
    ordered=True
).rename_categories(
    [
        "Sem estudo",
        "Primário",
        "Secundário inc.",
        "Secundário",
        "Faculdade inc. ou Técnico",
        "Faculdade +",
    ]
)

df_diabetes_tratado["FaixaRenda"] = pd.Categorical(
    df_diabetes_tratado["FaixaRenda"],
    ordered=True
).rename_categories(
    [
        "< $10.000",
        "$10.000-$14.999",
        "$15.000-$19.999",
        "$20.000-$24.999",
        "$25.000-$34.999",
        "$35.000-$49.999",
        "$50.000-$74.999",
        "$75.000+",
    ]
)

df_diabetes_tratado.head()

,Diabetes,PressaoAlta,ColesterolAlto,ColesterolExame,IMC,Fumante,AVC,ProblemaCardiaco,AtividadeFisica,ComeFrutas,ComeLegumes,ConsumoBebidaAlcoolica,PlanoSaude,SemDinheiroConsultas,SaudeGeral,DiasProblemasMentais,DiasProblemasFisicos,DificuldadeAndar,Genero,FaixaIdade,Ensino,FaixaRenda
0,Não,Sim,Não,Sim,26.0,Não,Não,Não,Sim,Não,Sim,Não,Sim,Não,Boa,5.0,30.0,Não,Masculino,35-39,Faculdade +,$75.000+
1,Não,Sim,Sim,Sim,26.0,Sim,Sim,Não,Não,Sim,Não,Não,Sim,Não,Boa,0.0,0.0,Não,Masculino,75-79,Faculdade +,$75.000+
2,Não,Não,Não,Sim,26.0,Não,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Excelente,0.0,10.0,Não,Masculino,80+,Faculdade +,$75.000+
3,Não,Sim,Sim,Sim,28.0,Sim,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Boa,0.0,3.0,Não,Masculino,70-74,Faculdade +,$75.000+
4,Não,Não,Não,Sim,29.0,Sim,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Muito boa,0.0,0.0,Não,Femenino,55-59,Faculdade inc. ou Técnico,$75.000+

## Tratamento Numerico

## Resumindo os dados numéricos

Nesta etapa, observamos um resumo estatístico das variáveis numéricas.

In [11]:
df_diabetes_tratado.describe()

                IMC  DiasProblemasMentais  DiasProblemasFisicos
count  70692.000000          70692.000000          70692.000000
mean      29.856985              3.752037              5.810417
std        7.113954              8.155627             10.062261
min       12.000000              0.000000              0.000000
25%       25.000000              0.000000              0.000000
50%       29.000000              0.000000              0.000000
75%       33.000000              2.000000              6.000000
max       98.000000             30.000000             30.000000

Aqui verificamos se os valores da coluna de dias de problemas físicos estão representados como números inteiros.

In [12]:
df_diabetes_tratado['DiasProblemasFisicos'].apply(float.is_integer).all()

True

Identificando as colunas numéricas

In [13]:
coluna_numericas = df_diabetes_tratado.select_dtypes(include='number').columns.to_list()

coluna_numericas

['IMC', 'DiasProblemasMentais', 'DiasProblemasFisicos']

## Ajustando os tipos numéricos

Aqui convertemos as colunas numéricas para um formato inteiro mais adequado e econômico.

**Por que fazer isso?**
Isso deixa os dados mais organizados e pode reduzir o espaço utilizado pela base.

In [14]:
for coluna in coluna_numericas:
    df_diabetes_tratado[coluna] = pd.to_numeric(
        df_diabetes_tratado[coluna],
        downcast='integer'
    )

df_diabetes_tratado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Diabetes                70692 non-null  category
 1   PressaoAlta             70692 non-null  category
 2   ColesterolAlto          70692 non-null  category
 3   ColesterolExame         70692 non-null  category
 4   IMC                     70692 non-null  int8
 5   Fumante                 70692 non-null  category
 6   AVC                     70692 non-null  category
 7   ProblemaCardiaco        70692 non-null  category
 8   AtividadeFisica         70692 non-null  category
 9   ComeFrutas              70692 non-null  category
 10  ComeLegumes             70692 non-null  category
 11  ConsumoBebidaAlcoolica  70692 non-null  category
 12  PlanoSaude              70692 non-null  category
 13  SemDinheiroConsultas    70692 non-null  category
 14  SaudeGeral              70692 non-null  category
 15  DiasProblemasMentais    70692 non-null  int8
 16  DiasProblemasFisicos    70692 non-null  int8
 17  DificuldadeAndar        70692 non-null  category
 18  Genero                  70692 non-null  category
 19  FaixaIdade              70692 non-null  category
 20  Ensino                  70692 non-null  category
 21  FaixaRenda              70692 non-null  category
dtypes: category(19), int8(3)
memory usage: 1.5 MB

## Salvando a base tratada

In [15]:
df_diabetes_tratado.to_parquet(DADOS_TRATADOS, index=False)
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Diabetes                70692 non-null  float64
 1   PressaoAlta             70692 non-null  float64
 2   ColesterolAlto          70692 non-null  float64
 3   ColesterolExame         70692 non-null  float64
 4   IMC                     70692 non-null  float64
 5   Fumante                 70692 non-null  float64
 6   AVC                     70692 non-null  float64
 7   ProblemaCardiaco        70692 non-null  float64
 8   AtividadeFisica         70692 non-null  float64
 9   ComeFrutas              70692 non-null  float64
 10  ComeLegumes             70692 non-null  float64
 11  ConsumoBebidaAlcoolica  70692 non-null  float64
 12  PlanoSaude              70692 non-null  float64
 13  SemDinheiroConsultas    70692 non-null  float64
 14  SaudeGeral              70692 non-null  float64
 15  DiasProblemasMentais    70692 non-null  float64
 16  DiasProblemasFisicos    70692 non-null  float64
 17  DificuldadeAndar        70692 non-null  float64
 18  Genero                  70692 non-null  float64
 19  FaixaIdade              70692 non-null  float64
 20  Ensino                  70692 non-null  float64
 21  FaixaRenda              70692 non-null  float64
dtypes: float64(22)
memory usage: 11.9 MB